export const comics = [
    {
        img:'assets/images/img-8.png'
    },
    {
        img:'assets/images/img-9.jpg'
    },
    {
        img:'assets/images/img-10.jpg'
    },
    {
        img:'assets/images/img-11.jpg'
    },
    {
        img:'assets/images/img-8.png'
    },
    {
        img:'assets/images/img-9.jpg'
    },
    {
        img:'assets/images/img-10.jpg'
    },
    {
        img:'assets/images/img-11.jpg'
    }
]